# Setup
title:               Heqing SHI
tagline:             ''
description:         'A reserved <a href="https://www.business-school.ed.ac.uk/" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://shiheqing.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Heqing Shi
  url:               https://twitter.com/mdo
  email:             Heqing.Shi@ed.ac.uk

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

markdown: kramdown
