# Setup
title:               Heqing SHI
tagline:             '施贺卿'
description:         '&#128075; I''m currently a PhD candidate (in FinTech) at <a href="https://www.business-school.ed.ac.uk/" 
                      target="_blank">UEBS</a>.<br><br>
                      Feel free to reach me via:<br> heqing[at]shi[at]ed[dot]ac[dot]uk &#128526'
url:                 https://shiheqing.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Heqing Shi
  url:               
  email:             Heqing.Shi@ed.ac.uk

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: G-8CWTH2F3FT

markdown: kramdown

#favicon: /public/emojo_favicon.ico