# Setup
title:               Heqing SHI
tagline:             ''
description:         'I''m currently a (3rd year) PhD (in Fintech) candidate at <a href="https://www.business-school.ed.ac.uk/" 
                      target="_blank">University of Edinburgh Business School</a>. &#128522; Feel free to reach me through Heqing.Shi[at]ed[dot]ac[dot]uk.'
url:                 https://shiheqing.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Heqing Shi
  url:               https://twitter.com/mdo
  email:             Heqing.Shi@ed.ac.uk

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

markdown: kramdown
