# Setup
title:               Heqing SHI
tagline:             ''
description:         '&#128075; I''m currently a (3rd year) PhD candidate (in FinTech) at <a href="https://www.business-school.ed.ac.uk/" 
                      target="_blank">University of Edinburgh Business School</a>. Feel free to reach me via Heqing.Shi[at]ed[dot]ac[dot]uk &#128526'
url:                 https://shiheqing.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Heqing Shi
  url:               https://twitter.com/mdo
  email:             Heqing.Shi@ed.ac.uk

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

markdown: kramdown

# Generate social links in footer.
social_links:
#  - { platform: devto,          user_url: "https://dev.to/jekyll" }
#  - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
#  - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
#  - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
  - { platform: github,         user_url: "https://github.com/uebs-stats-group" }
#  - { platform: gitlab,         user_url: "https://gitlab.com/jekyll" }
#  - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
#  - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
#  - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
#  - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jekyll" }
#  - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
#  - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
#  - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
#  - { platform: telegram,       user_url: "https://t.me/jekyll" }
#  - { platform: twitter,        user_url: "https://twitter.com/jekyllrb" }
#  - { platform: x,              user_url: "https://x.com/jekyllrb" }
#  - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }